### ISSUE TITLE
Not compatible with latest gravity forms

### ISSUE THREAD

**Issue by jaxrachel** [angelleye/gravity-forms-braintree#42] opened 2022-08-25 01:07 UTC
it doesn't work anymore, hasn't worked for months.

**Comment by drewangell** [comment] 2023-03-31 03:24
Hi.  I've finally had a chance to look into this and put some resources towards making it work.  However, I'm actually not able to reproduce any problem.  I have the latest version of GF running and I have both CC and ACH working fine.  Can you please elaborate on the issue you're having?

**Comment by jaxrachel** [comment] 2023-03-31 13:32
Well I haven't tried it in a long time but previously the error was,
whether we use the built-in Credit Card field or the AngelEye "Braintree
CC" credit card field, with all settings correct in the main Braintree
settings, field mapping, and feed settings, the payment does not process
and the form gives an error at the top "There was a problem with your
submission. Please review the fields below." but no fields are highlighted
with errors and the credit card fields are now missing.

If that's not happening for you anymore, then I can try it again and see
what happens! Standby.

**Comment by jaxrachel** [comment] 2023-03-31 13:47
Oh i think i found something. I have the conditional field "how would you like to pay?" with radio buttons for credit card or ACH. if they choose Credit card then the CC field appears, if they choose ACH then the Bank Account field appears. so, in my test, I chose Credit Card, tried to submit, got that error. If I then go back and change my selection to ACH, there is one subfield with an error, Account Number Verification: "We are unable to authorize bank account, This may have happened due to expired token, please try again."

so the problem seems to be that even though the field is optional, and when not selected via condition it's hidden, it still is trying to process via ACH. Can you fix that so if it's not a required field or if the field is hidden, it doesn't try to process CC/ACH?

we have to offer both ways to pay so we need them to be able to select one or the other.

**Comment by jaxrachel** [comment] 2023-03-31 14:09
[Here's a video recording of my test ](https://www.awesomescreenshot.com/video/16119487?key=24ee98ed636b4b84f5ee64ed426504b7)

**Comment by drewangell** [comment] 2023-04-06 08:30
I have a dev assigned to this, so we're working to get it all resolved.  I believe they already have it fixed, but we just need to do some final testing and then we'll publish an update.  We'll keep you posted!

**Comment by devchristina2** [comment] 2024-09-26 23:30
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.

**Closed by devchristina2** 2024-09-26 23:30 UTC
